### ISSUE TITLE
about test error!

### ISSUE THREAD

**Issue by zjisuccess** [czq142857/BAE-NET#1]
hello,i am interested in your contribution,when i run the test code,an error is meeting,try to figure it out,but it is not OK,can you give me some advice  how to solve this issue?

InternalError (see above for traceback): Blas SGEMM launch failed : m=1, n=128, k=16384
	 [[Node: encoder_1/conv_5/Conv3D = Conv3D[T=DT_FLOAT, data_format="NDHWC", dilations=[1, 1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](encoder_1/Maximum_3, **encoder/conv_5/Matrix/read)]]******

Looking forward to your early reply,thanks!
All the best.****

**Comment by czq142857** [comment]
I have not encountered similar errors before. But by Googling the error message you provided, it looks like a GPU memory issue. Please try the following:

1. Make sure your GPU and CPU have sufficient memory. Do not run multiple jobs on the same GPU.

2. Make sure your environment is following the "Dependencies" section of the README file: Python 3.5, TensorFlow 1.9.0, CUDA 9.1 and cuDNN 7.0 on Ubuntu 16.04. This is not strict. In fact, I can still run the code on my Windows 10 laptop with TensorFlow 1.15. But you need to install the correct version of cuda&cudnn. If your TensorFlow version and cuda&cudnn version do not match, you are likely to get weird errors.

Best,
Zhiqin

**Comment by zjisuccess** [comment]
> I have not encountered similar errors before. But by Googling the error message you provided, it looks like a GPU memory issue. Please try the following:
> 
> 1. Make sure your GPU and CPU have sufficient memory. Do not run multiple jobs on the same GPU.
> 2. Make sure your environment is following the "Dependencies" section of the README file: Python 3.5, TensorFlow 1.9.0, CUDA 9.1 and cuDNN 7.0 on Ubuntu 16.04. This is not strict. In fact, I can still run the code on my Windows 10 laptop with TensorFlow 1.15. But you need to install the correct version of cuda&cudnn. If your TensorFlow version and cuda&cudnn version do not match, you are likely to get weird errors.
> 
> Best,
> Zhiqin

Thank your for your great feedback.
