### ISSUE TITLE
Visualizing output for unsupervised trained BAE network

### ISSUE THREAD

**Issue by nka77** [czq142857/BAE-NET#10]
I am facing issues while visualizing the output for unsupervised trained BAE network.

I have trained the model on 02958343_car data using the following command:
`python main.py --train --L1reg --iteration 20000 --dataset 02958343_vox --data_dir ../RAdata/02958343_car --checkpoint_dir checkpoint_unsup --sample_dir ../RAdata/02958343_car  --real_size 32 --points_per_shape 8192`

In order to view the output of the model, I am using this:
`python main.py --recon --L1reg --iteration 20000 --dataset 02958343_vox --data_dir ../RAdata/02958343_car --checkpoint_dir checkpoint_unsup --sample_dir ../RAdata/02958343_car  --real_size 32 --points_per_shape 8192`

But this gives me the following error:
 ```  File "/home/nka77/sfuhome/BAE-NET/model.py", line 515, in test_dae
    for t in range(min(len(self.ref_voxels),16)):
AttributeError: 'IMSEG' object has no attribute 'ref_voxels'
```

Could you please guide me on how to debug this?
or suggest another way to visualize the output for unsupervised trained model?

_Please note that I am able to visualize for the supervised trained model._

**Comment by czq142857** [comment]
You need to specify the target shapes using "--supervision_list", which is a list of testing shapes:

```
python main.py --recon ... ... ... ... --supervision_list 02958343_vox.txt
```

**Comment by inavjotkaur** [comment]
I ran this: 
`python main.py --pointcloud --L1reg --iteration 20000 --dataset 02958343_vox --data_dir ../RAdata/02958343_car --checkpoint_dir checkpoint_unsup --sample_dir ../RAdata/02958343_car  --real_size 32 --points_per_shape 8192 --supervision_list obj_lst.txt`
where obj_lst.txt is the file already present in the 02958343_car folder.

But I am still getting the error:
```File "/sfuhome/BAE-NET/model.py", line 652, in test_pointcloud
    batch_voxels = self.ref_voxels[t:t+1]
AttributeError: 'IMSEG' object has no attribute 'ref_voxels'```

Do I need to create a new file?

**Comment by nka77** [comment]
I ran this:
`python main.py --pointcloud --L1reg --iteration 20000 --dataset 02958343_vox --data_dir ../RAdata/02958343_car --checkpoint_dir checkpoint_unsup --sample_dir ../RAdata/02958343_car --real_size 32 --points_per_shape 8192 **--supervision_list obj_lst.txt**`
where obj_lst.txt is the file already present in the 02958343_car folder.
But I am still getting the error:
    ``` batch_voxels = self.ref_voxels[t:t+1]
AttributeError: 'IMSEG' object has no attribute 'ref_voxels'```
**How to create the supervision_list?**

I also tried unsupervised training and prediction for chair using '03001627_vox.txt' as 'supervision_list' and it works.
Could you help me understand how to generate a similar '*_vox.txt' for '02958343_car'?

**Comment by nka77** [comment]
So simply renaming the file helped to resolve this :)

However, the result is not very good for cars using unsupervised training. Could you recommend number of iterations required to get decent result for cars?

**Comment by czq142857** [comment]
It is unlikely for BAE-Net to work well on cars, because the ground truth parts (hood, roof, wheel) are not volumetric. BAE-Net relies on reconstructing volumetric bodies to segment the shapes, therefore it cannot segment surface parts. If I remember correctly, you can get another set of segmented parts on cars (mirror, spoiler, wheel).

**Comment by nka77** [comment]
Is BAE-Net expected to perform good enough on cars using few-shot learning method?
Could you recommend some other way for part segmentation? My dataset consists of bus and truck models.

**Comment by czq142857** [comment]
Please try other segmentation method. BAE-Net cannot do well on car category.
