### ISSUE TITLE
Unsupervised segmentation results

### ISSUE THREAD

**Issue by haoyu6427** [czq142857/BAE-NET#11]
Hi Zhiqin,

Thank you for the great work! I'm trying to reproduce your unsupervised segmentation results. It seems like I can't get the results of the bag and cap categories the paper reported. The best results I got are 75.6 for bag category and 77.6 for cap category. Can you provide the parameters you set for unsupervised training, also the branch number and output shape of fully-connected layers? I'd apperate it if you can help. 

Thank you

**Comment by czq142857** [comment]
For unsupervised training, you need to set the width (number of neurons) of the MLP to {3072-384-12}. In the current code, it is {1024-256-8} for one-shot training.

Also, you could try uncomment line 259 in model.py
```
#Sometimes it is beneficial to let the initial value of the output equal to 0 (rather than 0.5).
#Uncomment the following line to move the initial output value from 0.5 to 0.
#h3 = h3*2-1
```
