### ISSUE TITLE
Point cloud as input

### ISSUE THREAD

**Issue by ardianumam** [czq142857/BAE-NET#14]
Hi,

Thanks for the insightful work! 
I know that the method accepts: (i) data points with (2) their association 0 or 1 value for the inside or outside label, and (3) data voxel. I wonder, if my dataset only has point clouds data (not a mesh model), thus we cannot build data (2) and (3). In this case, can we still use or modify BAENet to do co-segmentation on my dataset (point clouds)? Many thanks!

**Comment by czq142857** [comment]
I think it is not possible to apply BAE-Net unless you have solid shapes. Point clouds are points on the surface of the shapes so they will not work. You need to somehow convert them into solid shapes.
