### ISSUE TITLE
Could the network be trained in class-agnostic manner?

### ISSUE THREAD

**Issue by curiosity654** [czq142857/BAE-NET#5]
Hi Zhiqi,
First, thank you for the amazing work. I find the models are trained with each class, unlike the full-supervised network that provides one network for all the classes. So I wonder could this network be trained in a class-agnostic manner?

**Comment by czq142857** [comment]
Sadly, no. The network relies on the part-level correspondences between shapes in the training set. Therefore, it makes sense to train chairs and tables together (as shown in the paper), but chairs and airplanes do not make sense.
