### ISSUE TITLE
How to test with unsupervised?

### ISSUE THREAD

**Issue by duzhenjiang113** [czq142857/BAE-NET#6]
hi, great work!!! could you please tell me how to test with unsupervised? thanks a lot!

**Comment by czq142857** [comment]
To train or visualize the unsupervised, please check README.md.

To test IOU, check this thread:
https://github.com/czq142857/BAE-NET/issues/3

**Comment by duzhenjiang113** [comment]
thanks for your reply. it seems that only remove the flag --supervise will also meet some problems:
AttributeError: 'IMSEG' object has no attribute 'ref_b_point_num

**Comment by czq142857** [comment]
I think it happened in the pre-training phase (of one-shot training). You need to also remove the "--pretrain_iters" and "--retrain_iters" parameters. Here is a side-by-side comparison of the one-shot training command and the unsupervised training command in the readme page:

python main.py --train --L1reg **--supervised** --iteration 200000 **--pretrain_iters 3000** **--retrain_iters 4** --dataset 03001627_vox --data_dir ./data/03001627_chair/ **--checkpoint_dir checkpoint_1shot_1_3000** **--supervision_list ref1.txt** --sample_dir samples/03001627_chair  --real_size 32 --points_per_shape 8192

python main.py --train --L1reg --iteration 200000 --dataset 03001627_vox --data_dir ./data/03001627_chair/ **--checkpoint_dir checkpoint_unsup** --sample_dir samples/03001627_chair  --real_size 32 --points_per_shape 8192

Sorry for the confusion.
