### ISSUE TITLE
Code for mod-IoU

### ISSUE THREAD

**Issue by MrMois** [czq142857/BAE-NET#8]
Hello,

how do you calculate the mod-IoU score as listed in Table 1 of the paper? I didn't find it in the code.

Greetings!

**Comment by czq142857** [comment]
https://github.com/czq142857/BAE-NET/issues/3

**Comment by MrMois** [comment]
So is the grouping done in the ground truth or in the network output?

**Comment by czq142857** [comment]
If you want to merge some ground truth parts into one semantic part (for example, table leg + table support -> table leg), you need to also perform the grouping on the ground truth. Otherwise, you just need to do it on the network output.

**Comment by MrMois** [comment]
Okay, thanks for the quick answer! To cite the paper: "modified IOU is IOU measured against both parts and part combinations in the ground truth". Does this mean you compute the IOU of your output labeling for all possible ground truth combinations and take the maximum? And how does this work for shapes with two labels (e.g. skateboard as deck; wheel+bar)?

**Comment by czq142857** [comment]
No. The combination is defined manually for both the grouping of output branches and the grouping of the ground truth labels. It is easier this way since you only need to look at a few output examples to decide which branch is which part.

**Comment by MrMois** [comment]
Ah. So if a single decoder neuron of the trained network is voting for both "body" and "tail" in category airplane (seen after manual inspection), you combine "body" and "tail" to a "body+tail" part in the ground truth for all examples? But doesn't this allow for a trivial single lable solution with mod-IoU of "1"?

**Comment by czq142857** [comment]
Indeed. The single label solution would be a failure case.

**Comment by MrMois** [comment]
Alright, now I understand it. Thanks for your quick and helpful answers!
